### ISSUE TITLE
Can not instantiate client in IRB

### ISSUE THREAD

**Issue by jacobat** [yousty/event_store_client#36]
```
$ irb -r bundler/setup -r event_store_client
irb(main):001:0> EventStoreClient::Client.new
/Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/reline/version.rb:2: warning: already initialized constant Reline::VERSION
/Users/jacob/.gem/ruby/2.7.2/gems/reline-0.2.0/lib/reline/version.rb:2: warning: previous definition of VERSION was here
[... many more errors ...]
/Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:831: warning: previous definition of ATTR_TTY was here
/Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/irb.rb:816: warning: already initialized constant IRB::Irb::ATTR_PLAIN
/Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:833: warning: previous definition of ATTR_PLAIN was here
=> #<EventStoreClient::Client:0x00007fd310162c50 @threads=[], @connection=#<EventStoreClient::GRPC::Client:0x00007fd30f12a108>, @error_handler=nil, @service_name="default", @broker=#<EventStoreClient::Broker:0x00007fd30f129d48 @connection=#<EventStoreClient::GRPC::Client:0x00007fd30f12a108>, @threads=[]>, @subscriptions=#<EventStoreClient::Subscriptions:0x00007fd30f128d08 @connection=#<EventStoreClient::GRPC::Client:0x00007fd30f12a108>, @service="default", @subscriptions=[]>>
Traceback (most recent call last):
        29: from /Users/jacob/.gem/ruby/2.7.2/bin/irb:23:in `<main>'
        28: from /Users/jacob/.gem/ruby/2.7.2/bin/irb:23:in `load'
        27: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        26: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:400:in `start'
        25: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:471:in `run'
        24: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:471:in `catch'
        23: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:472:in `block in run'
        22: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:537:in `eval_input'
        21: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:170:in `each_top_level_statement'
        20: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:170:in `catch'
        19: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:171:in `block in each_top_level_statement'
        18: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:171:in `loop'
        17: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:174:in `block (2 levels) in each_top_level_statement'
        16: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/irb/ruby-lex.rb:182:in `lex'
        15: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:518:in `block in eval_input'
        14: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/irb.rb:704:in `signal_status'
        13: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb.rb:519:in `block (2 levels) in eval_input'
        12: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/irb/input-method.rb:294:in `gets'
        11: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
        10: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
         9: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/reline.rb:175:in `readmultiline'
         8: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/reline.rb:235:in `inner_readline'
         7: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/reline/line_editor.rb:315:in `rerender'
         6: from /Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/reline/line_editor.rb:70:in `check_multiline_prompt'
         5: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:68:in `block in set_input'
         4: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:68:in `each'
         3: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:73:in `block (2 levels) in set_input'
         2: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:73:in `each_line'
         1: from /Users/jacob/.gem/ruby/2.7.2/gems/irb-1.3.0/lib/irb/ruby-lex.rb:75:in `block (3 levels) in set_input'
/Users/jacob/.rubies/ruby-2.7.2/lib/ruby/2.7.0/irb/ruby-lex.rb:124:in `check_state': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

**Comment by swilgosz** [comment]
@jacobat I've updated the README and the setup script. It uses the docker-compose now as installing GRPC for ruby in various systems generates some troubles.

By using docker the issue more or less disappears.

Please let me know if that simplifies the way to run the project for you.

**Comment by jacobat** [comment]
There appears to be a missing `.env_test` file. Running `bin/setup` ends with:

```
...
[BGN] Copying tags from /host_sync to /app_sync
[END] Copying tags
[BGN] Copying testing.rb from /host_sync to /app_sync
[END] Copying testing.rb
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 09:34:45.86 on 09 Mar 2021
Saving synchronizer state
Synchronization complete at 09:34:45  (29 items transferred, 0 skipped, 0 failed)
chown ing file to uid 0
real    0m 1.26s
user    0m 0.10s
sys     0m 0.10s
b11a7431bc37feb5f2d274669be61a7fd21467c6b95b3efb204d53791f9346d2
     success  Sync container started
     success  Starting Docker-Sync in the background
docker-compose run specs bundle install
+ docker-compose run specs bundle install
ERROR: Couldn't find env file: /Users/u0157733/code/ruby/event_store_client/.env_test
```

**Comment by jacobat** [comment]
I'm also seeing:

```
ERROR: pull access denied for yousty/esc, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by swilgosz** [comment]
Yeah, it's configured to have prebuilt images. i will adjust today, thanks for mentioning it:)

**Comment by swilgosz** [comment]
@jacobat please let me know if now everything is solved for you. 

I refer to the extracted dev setup doc: https://github.com/yousty/event_store_client/blob/master/docs/eventstore_server_setup.md

I've improved the setup to:
- automatically build image
- automatically set proper env variables
- added instructions how to run the sandbox scripts `bin/grpc` & `bin/http`
